var wordpool = {
    animals:   [{word: "animals", image:"http://questgarden.com/97/03/8/100328182544/images/collage.jpg"}, 
                {word: "horse", image: "http://buzzsharer.com/wp-content/uploads/2015/06/beautiful-running-horse.jpg"}, 
                {word: "duck", image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Male_mallard_duck_2.jpg"}, 
                {word: "rabbit", image: "http://sciencenordic.com/sites/default/files/imagecache/620x/rabbit_0.jpg"}, 
                {word: "mouse", image: "http://vrjournal.com/wp-content/uploads/2015/10/Mouse-Tales-Neuroscientists-Work-on-Virtual-Reality-System-Using-Mice-Whiskers.jpg"}, 
                {word: "goose", image: "http://justinhackworth.com/canada-goose-01.jpg"}, 
                {word: "penguin", image: "http://weknowyourdreamz.com/images/penguin/penguin-09.jpg"}, 
                {word: "whale", image: "http://images.express.co.uk/img/dynamic/78/590x/secondary/16711.jpg"}, 
                {word: "shark", image: "http://a.abcnews.go.com/images/US/gty_reef_shark_mm_mm_150615_12x5_1600.jpg"}, 
                {word: "dinosaur", image: "http://www.paleophilatelie.eu/description/stamps/detail/jordan/wp1_hd.jpg"},  
                {word: "spider", image: "http://entnemdept.ufl.edu/creatures/URBAN/SPIDERS/black_widow_spider02.jpg"}, 
                {word: "bear", image: "http://hobopace.com/wp-content/uploads/2015/07/wallpaper-brown-bear-family.jpg"}, 
                {word: "fox", image: "http://images.wisegeek.com/red-fox.jpg"}, 
                {word: "deer", image: "http://i.onionstatic.com/clickhole/1914/5/original/1200.jpg"}, 
                {word: "frog", image: "http://www.adirondackexplorer.org/wp-content/uploads/2009/05/Mink-frog.jpg"},  
                {word: "elephant", image: "http://www.spirit-animals.com/wp-content/uploads/2012/09/Elephant.jpg"}, 
                {search: "gray wolf",word: "wolf", image: "http://jon-atkinson.com/Large%20Images%201/Grey%20Wolf%203.jpg"}, 
                {word: "owl", image: "http://dreamatico.com/data_images/owl/owl-4.jpg"}, 
                {word: "chicken", image: "https://www.raspberrypi.org/wp-content/uploads/2015/06/Poltava_chicken_breed_male1.jpg"}, 
                {word: "bird", image: "http://www.nashvillenewzine.com/Photos/Birds/BirdCollage2.jpg"}, 
                {word: "starfish", image: "https://upload.wikimedia.org/wikipedia/commons/d/de/Royal_starfish_(Astropecten_articulatus)_on_the_beach.jpg"}, 
                {word: "monkey", image: "http://alltotems.com/wp-content/uploads/2013/03/monkey-meaning-and-symbol.jpg"}, 
                {word: "parrot", image: "http://cdn.pearltrees.com/s/pic/la/parrot-bird-43135399"}, 
                {search: "turkey vulture", word: "turkey", image: "http://animaliaz-life.com/data_images/turkey/turkey2.jpg"},  
                {word: "kitten", image: "http://www.theromantic.com/wp-content/uploads/2015/07/kitten-worst-romantic-gifts.jpg"}, 
                {word: "crab", image: "http://cdn0.dailydot.com/cache/e1/93/e1931ae0fa39e84de9bd940e343f5d58.jpg"}, 
                {word: "lobster", image: "http://i.huffpost.com/gen/1951550/images/n-LOBSTER-GOPRO-628x314.jpg"}, 
                {word: "pig", image: "http://oldcastlelabs.ie.s205606.gridserver.com/wp-content/uploads/2012/06/497730-pig.jpg"}, 
                {word: "sheep", image: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Lleyn_sheep.jpg"}, 
                {word: "goat", image: "http://www.motherjones.com/files/goat.jpg"}, 
                {word: "ostrich", image: "http://www.onekind.org/uploads/a-z/az_ostriches.jpg"}, 
                {word: "flamingo", image: "http://www.liveanimals.tv/wp-content/uploads/2014/03/flamingo-webcam.jpg"}, 
                {search: "seal pinniped", word: "seal", image: "http://ccisolar.caltech.edu/images/filecabinet/folder23/seal-picture.jpg"}, 
                {search: "sea lion", word: "sea lion", image: "http://localtvwiti.files.wordpress.com/2013/07/sea-lion.jpg?w=770"}, 
                {word: "lion", image: "http://animaliaz-life.com/data_images/lion/lion5.jpg"}, 
                {word: "kangaroo", image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/RedRoo.JPG"}, 
                {word: "snake", image: "https://i.ytimg.com/vi/sPSFYGdoQyc/maxresdefault.jpg"}, 
                {word: "cobra", image: "https://tbashoestring.files.wordpress.com/2011/03/midigama-feb-11_183-post.jpg"}, 
                {word: "insect", image: "http://www.yourbugman.com/siteimages/insect%20pictures_AutoCollage_10_four.jpg"}, 
                {word: "reptile", image: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Extant_reptilia.jpg"},  
                {word: "butterfly", image: "http://kids.nationalgeographic.com/content/dam/kids/photos/animals/Bugs/H-P/monarch-butterfly-orange-flower.jpg"}, 
                {word: "turtle", image: "http://www.ecology.com/wp-content/uploads/2012/05/eastern-box-turtle.jpg"}, 
                {word: "lizard", image: "http://animals.sandiegozoo.org/sites/default/files/juicebox_slides/red_headed_rock_agama.jpg"}, 
                {word: "squid", image: "http://cx.aos.ask.com/question/aq/1400px-788px/small-squid-eat_458d52bfa00407b.jpg"}, 
                {word: "octopus", image: "http://animal-dream.com/data_images/octopus/octopus8.jpg"}, 
                {word: "pelican", image: "https://naturetime.files.wordpress.com/2014/01/white-pelican-pouch.jpg"}, 
                {word: "caterpillar", image: "http://www.backyardnature.net/pix/b-swal-c.jpg"}, 
                {word: "rooster", image: "http://images.animalpicturesociety.com/images/12/img_2039.jpg"}, 
                {word: "tiger", image: "http://weknowyourdreamz.com/images/tiger/tiger-09.jpg"}, 
                {word: "hamster", image: "http://i2.mirror.co.uk/incoming/article3461309.ece/ALTERNATES/s615/Hamster.jpg"}, 
                {word: "gorilla", image: "http://www.galiwango.com/wp-content/uploads/solomon_w_jagwe_galiwango_film_conservation_front_feature_061.jpg"}]

};

